export const FRONTEND_ROUTES = {
  home: '/',
  about: '/about',
  category: '/category/:categoryUid',
  project: '/project/:projectUid',
  signIn: '/sign-in',
  dashboard: '/dashboard',
  dashboardProjects: '/dashboard',
  dashboardAddProject: '/dashboard/add-project',
  dashboardAddProjectTranslation: '/dashboard/add-project/translation/:projectUid',
  dashboardCategories: '/dashboard/categories',
  dashboardEditProject: '/dashboard/edit-project/:projectUid/:projectLocale',
  dashboardChangeProjectFiles: '/dashboard/edit-project/:projectUid/files',
  dashboardChangeProjectCategory: '/dashboard/change-project-category/:projectUid',
};
